import { execSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import fg from 'fast-glob'
import type { BuildArtifact, DetectResult, ResolvedConfig, Target } from './types.js'
import { log, pc } from './logger.js'
import { bundleApp, packageNameOf, type BundleResult } from './bundle.js'
import { obfuscateCode } from './obfuscate.js'
import { pack } from './pack.js'
import { installCmd } from './pm.js'
import { scanNatives } from './natives.js'
import { stageNativePackages } from './stage-natives.js'
import { buildLibManifest, writeExtractPrelude } from './extract-libs.js'
import { gatherStaticDirs, writeStaticEnvPrelude } from './gather.js'
import { resolveEntryCandidates } from './detect.js'

export interface RunResult {
  artifacts: BuildArtifact[]
  bytecodeFailures: string[]
  warnings: string[]
}

export function formatBytes(n: number): string {
  if (n <= 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB']
  const i = Math.min(units.length - 1, Math.floor(Math.log(n) / Math.log(1024)))
  return `${(n / 1024 ** i).toFixed(i === 0 ? 0 : 1)} ${units[i]}`
}

export function hostTarget(): Target {
  const platform =
    process.platform === 'darwin' ? 'macos' : process.platform === 'win32' ? 'win' : 'linux'
  const arch: Target['arch'] =
    process.arch === 'arm64'
      ? 'arm64'
      : process.arch === 'x64'
        ? 'x64'
        : process.arch === 'arm'
          ? 'armv7'
          : 'x64'
  return { platform, arch }
}

/**
 * Decide whether a build needs Docker. Two host-mode hazards force it:
 *  1. Native addons (.node) are machine code — they can't be cross-compiled on the host.
 *  2. pkg's V8 bytecode is generated by the *host* runtime; embedding it in a different
 *     OS/arch target produces a binary V8 rejects at startup ("bytecode cache" error).
 * Either hazard, combined with a target that isn't exactly this host, requires Docker.
 */
export function decideMode(config: ResolvedConfig): 'host' | 'docker' {
  const host = hostTarget()
  const crossTargets = config.targets.filter(
    (t) => t.platform !== host.platform || t.arch !== host.arch,
  )
  const reasons: string[] = []
  if (crossTargets.length > 0) {
    if (config.bytecode) reasons.push('V8 bytecode is host-specific and is rejected cross-OS/arch')
    if (config.externals.length > 0)
      reasons.push(`native addons (${config.externals.join(', ')}) need per-arch builds`)
  }
  const needsDocker = reasons.length > 0

  if (config.mode === 'host') {
    if (needsDocker) {
      log.warn(
        `mode=host but the produced binaries are likely to fail at runtime: ${reasons.join('; ')}. ` +
          `The reliable options are --mode docker, or --no-bytecode for a pure-JS cross-OS build.`,
      )
    }
    return 'host'
  }
  if (config.mode === 'docker') return 'docker'
  return needsDocker ? 'docker' : 'host'
}

function sh(cmd: string, cwd: string): void {
  execSync(cmd, { cwd, stdio: 'inherit' })
}

const FRESH_EXCLUDE = new Set([
  'node_modules',
  '.git',
  '.node-bundle',
  'node-bundle-out',
  '.turbo',
  'coverage',
  '.cache',
])

/** Copy a project's source (no node_modules) to a writable temp dir, so a fresh
 *  per-arch install/build can run without mutating a read-only mounted project. */
function prepareFreshSource(srcDir: string): string {
  const dest = path.join(os.tmpdir(), 'node-bundle-src')
  fs.rmSync(dest, { recursive: true, force: true })
  fs.mkdirSync(dest, { recursive: true })
  fs.cpSync(srcDir, dest, {
    recursive: true,
    filter: (s) => !FRESH_EXCLUDE.has(path.basename(s)),
  })
  return dest
}

function resolveEntry(config: ResolvedConfig, detected: DetectResult): string {
  if (config.entry) {
    const abs = path.resolve(config.projectDir, config.entry)
    if (!fs.existsSync(abs)) throw new Error(`--entry "${config.entry}" not found (${abs})`)
    return abs
  }
  // Recompute candidates against the *active* project dir — it may differ from the
  // one detection used (e.g. after a --fresh-install copy to a temp directory).
  const candidates = resolveEntryCandidates(config.projectDir, detected.pkgJson)
  for (const c of candidates) {
    if (fs.existsSync(c)) return c
  }
  throw new Error(
    'Could not locate a compiled entry file. Build your app first, or pass --entry <post-build .js>.\n' +
      `  Looked for:\n${candidates.map((c) => `    - ${c}`).join('\n')}`,
  )
}

/** Build the per-arch executables on this machine (no Docker). */
export async function runHost(configIn: ResolvedConfig, detected: DetectResult): Promise<RunResult> {
  const config: ResolvedConfig = configIn.freshInstall
    ? { ...configIn, projectDir: prepareFreshSource(configIn.projectDir) }
    : configIn
  const { projectDir } = config
  const tmpDir = path.join(projectDir, '.node-bundle', 'tmp')

  // 1. Dependencies
  log.step('Dependencies')
  await log.groupAsync(async () => {
    const hasNodeModules = fs.existsSync(path.join(projectDir, 'node_modules'))
    if (config.freshInstall || !hasNodeModules) {
      const cmd = installCmd(detected.packageManager, projectDir)
      log.info(`Installing with ${detected.packageManager}: ${pc.bold(cmd)}`)
      sh(cmd, projectDir)
    } else {
      log.success('node_modules present')
    }
  })

  // 2. Project's own build (tsc/webpack/nest)
  log.step('Project build')
  await log.groupAsync(async () => {
    if (config.runProjectBuild && config.buildCommand) {
      log.info(`Running: ${pc.bold(config.buildCommand)}`)
      sh(config.buildCommand, projectDir)
      log.success('Build complete')
    } else if (!config.runProjectBuild) {
      log.info('Skipped (--no-build)')
    } else {
      log.info('No build command detected — assuming app is already JavaScript')
    }
  })

  // Re-scan natives now that everything is installed/built.
  const nativeScan = await scanNatives(projectDir)
  const natives = nativeScan.packages
  const sharedLibs = nativeScan.sharedLibPackages
  const externals = Array.from(new Set([...config.externals, ...natives, ...sharedLibs]))

  const entry = resolveEntry(config, detected)
  log.step('Bundle & protect')
  fs.rmSync(tmpDir, { recursive: true, force: true })
  fs.mkdirSync(tmpDir, { recursive: true })

  const finalBundle = path.join(tmpDir, 'bundle.cjs')
  const entryForPkg = finalBundle

  // Stage externalized packages next to the bundle so their runtime require()s
  // resolve inside the snapshot (pnpm symlink layouts break pkg's own tracing).
  const stagedNatives = stageNativePackages(projectDir, tmpDir, nativeScan.files, externals)
  if (stagedNatives.staged.length) {
    log.group(() =>
      log.info(
        `Staged ${stagedNatives.staged.length} runtime package(s) for embedding: ${stagedNatives.staged.join(', ')}`,
      ),
    )
  }
  for (const name of stagedNatives.unresolved) {
    log.warn(`External package "${name}" not found in node_modules — its require() may fail at runtime.`)
  }

  // Shared libraries can't be dlopen'ed from the snapshot — inject a prelude
  // that extracts those packages to a real dir and redirects their resolution.
  const libManifest = buildLibManifest(tmpDir, sharedLibs, stagedNatives.staged)
  const inject = libManifest.length ? [writeExtractPrelude(tmpDir, libManifest)] : []
  if (libManifest.length) {
    log.group(() =>
      log.info(
        `Shared-library package(s) will self-extract at startup: ${libManifest.map((m) => m.name).join(', ')}`,
      ),
    )
  }

  // Static dirs: embed into the binary and/or copy sidecar into the output dir.
  const gathered = gatherStaticDirs(config.staticDirs, projectDir, tmpDir, config.outDir)
  const staticEnvPrelude = writeStaticEnvPrelude(tmpDir, gathered.embedManifest)
  if (staticEnvPrelude) inject.push(staticEnvPrelude)

  const logExtras = (r: BundleResult) => {
    for (const w of r.warnings) log.warn(w)
    if (r.externalizedMissing.length) {
      const shown = r.externalizedMissing.slice(0, 8).join(', ')
      const more = r.externalizedMissing.length > 8 ? `, … (+${r.externalizedMissing.length - 8})` : ''
      log.info(`Auto-externalized ${r.externalizedMissing.length} unresolved/optional import(s): ${shown}${more}`)
    }
  }

  const result = await log.groupAsync(async (): Promise<BundleResult> => {
    log.info(`Entry: ${pc.bold(path.relative(projectDir, entry) || entry)}`)
    if (externals.length) log.info(`External (native) packages: ${externals.join(', ')}`)
    const esTarget = config.esbuildTarget

    if (config.obfuscate === 'off') {
      const r = await bundleApp({ entry, outFile: finalBundle, externals, target: esTarget, minify: false, projectDir, inject })
      log.success(`Bundled → ${formatBytes(r.size)}`)
      logExtras(r)
      log.warn('Obfuscation disabled — only bytecode protects this build.')
      return r
    }

    // Stage A — bundle ONLY the app's own code (all packages external). Small input
    // → obfuscation is fast and targets your IP, not megabytes of third-party deps.
    const appOnly = path.join(tmpDir, 'app.cjs')
    const a = await bundleApp({
      entry,
      outFile: appOnly,
      externals,
      target: esTarget,
      minify: false,
      externalizeAllPackages: true,
      projectDir,
    })
    log.success(`App code bundled → ${formatBytes(a.size)} ${pc.dim(`(scope for obfuscation)`)}`)

    // Reserve every specifier the app references so the obfuscator keeps them as
    // literal require()s — otherwise Stage B can't inline them / pkg can't trace them.
    const reserved = Array.from(
      new Set([...externals, ...a.externalized, ...a.externalized.map(packageNameOf)]),
    )
    const obfApp = path.join(tmpDir, 'app.obf.cjs')
    fs.writeFileSync(obfApp, obfuscateCode(fs.readFileSync(appOnly, 'utf8'), config.obfuscate, reserved))
    log.success(`Obfuscated app code (${config.obfuscate})`)

    // Stage B — bundle the obfuscated app together with all dependencies inlined.
    const b = await bundleApp({ entry: obfApp, outFile: finalBundle, externals, target: esTarget, minify: false, projectDir, inject })
    log.success(`Bundled with deps inlined → ${formatBytes(b.size)}`)
    logExtras(b)
    return b
  })

  // Inlined packages that use __dirname/__filename read sibling files at runtime
  // (protos, templates, certs, wasm…) — embed their non-code files so those reads
  // resolve inside the snapshot at the preserved paths.
  const autoAssets: string[] = []
  for (const pkgDir of result.dirnamePackages) {
    const files = fg.sync(['**/*'], {
      cwd: pkgDir,
      dot: false,
      followSymbolicLinks: false,
      suppressErrors: true,
      onlyFiles: true,
      ignore: ['**/*.js', '**/*.cjs', '**/*.mjs', '**/*.ts', '**/*.map', '**/*.md', '**/node_modules/**', '**/LICENSE*', '**/license*'],
    })
    for (const f of files) autoAssets.push(path.join(pkgDir, f))
  }
  if (autoAssets.length) {
    const total = autoAssets.reduce((n, f) => n + (fs.statSync(f).size || 0), 0)
    log.group(() =>
      log.info(
        `Auto-embedding ${autoAssets.length} runtime data file(s) (${formatBytes(total)}) from ${result.dirnamePackages.length} package(s) that use __dirname`,
      ),
    )
  }

  // 4. Write the pkg config + pack per target.
  writePkgConfig(
    tmpDir,
    projectDir,
    { ...config, assets: [...config.assets, ...autoAssets] },
    entryForPkg,
    stagedNatives.staged.length > 0,
    gathered.embedAssets,
  )

  log.step('Pack (bytecode + executable)')
  const outcome = await pack({
    configDir: tmpDir,
    outDir: config.outDir,
    name: config.name,
    ext: config.ext,
    nodeRange: config.nodeRange,
    targets: config.targets,
    bytecode: config.bytecode,
  })

  if (!config.keepTemp) fs.rmSync(path.join(projectDir, '.node-bundle'), { recursive: true, force: true })

  return {
    artifacts: outcome.artifacts,
    bytecodeFailures: outcome.bytecodeFailures,
    warnings: result.warnings,
  }
}

/** Write the temporary package.json that tells pkg the entry + assets. */
export function writePkgConfig(
  tmpDir: string,
  projectDir: string,
  config: ResolvedConfig,
  entryForPkg: string,
  includeStagedModules = false,
  /** Extra globs already relative to tmpDir (embedded static dirs). */
  tmpRelativeAssets: string[] = [],
): void {
  // pkg resolves asset globs relative to this package.json — rewrite project-relative
  // paths/globs to be relative to tmpDir.
  const toTmpRel = (p: string) =>
    path.relative(tmpDir, path.resolve(projectDir, p)).split(path.sep).join('/')

  const assets = Array.from(new Set([...config.assets.map(toTmpRel), ...tmpRelativeAssets]))
  // The staged native/external packages live inside tmpDir itself.
  if (includeStagedModules) assets.push('node_modules/**/*')

  const pkgConfig = {
    name: config.name,
    version: '1.0.0',
    bin: path.basename(entryForPkg),
    pkg: {
      assets,
      scripts: [] as string[],
    },
  }
  fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify(pkgConfig, null, 2))
}

export function summarize(result: RunResult, config: ResolvedConfig): void {
  log.plain('')
  log.step('Done')
  log.group(() => {
    for (const a of result.artifacts) {
      const ok = a.size > 0
      const tag = `${a.target.platform}-${a.target.arch}`
      if (ok) {
        log.success(
          `${pc.bold(path.relative(process.cwd(), a.path))}  ${pc.dim(`(${tag}, ${formatBytes(a.size)})`)}`,
        )
      } else {
        log.error(`${tag}: pkg did not produce an output file`)
      }
    }
    if (result.bytecodeFailures.length) {
      log.warn(
        `Bytecode fell back to source for: ${result.bytecodeFailures.join(', ')}. ` +
          `Run with --mode docker to generate bytecode natively per architecture.`,
      )
    }
  })
}
